
// user constants
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

// product constants
export const LIST_PRODUCTS_REQUEST = "LIST_PRODUCTS_REQUEST";
export const LIST_PRODUCTS_SUCCESS = "LIST_PRODUCTS_SUCCESS";
export const LIST_PRODUCTS_FAIL = "LIST_PRODUCTS_FAIL";

export const LIST_MYPRODUCTS_REQUEST = "LIST_MYPRODUCTS_REQUEST";
export const LIST_MYPRODUCTS_SUCCESS = "LIST_MYPRODUCTS_SUCCESS";
export const LIST_MYPRODUCTS_FAIL = "LIST_MYPRODUCTS_FAIL";

export const DETAIL_PRODUCT_REQUEST = "DETAIL_PRODUCT_REQUEST";
export const DETAIL_PRODUCT_SUCCESS = "DETAIL_PRODUCT_SUCCESS";
export const DETAIL_PRODUCT_FAIL = "DETAIL_PRODUCT_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESSS = "DELETE_PRODUCT_SUCCESSS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const MY_PRODUCTS_REQUEST = "MY_PRODUCTS_REQUEST";
export const MY_PRODUCTS_SUCCESS = "MY_PRODUCTS_SUCCESS";
export const MY_PRODUCTS_FAIL = "MY_PRODUCTS_FAIL";

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST";
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORY_FAIL = "GET_PRODUCTS_BY_CATEGORY_FAIL";

export const GET_PRODUCTS_BY_PUBLICATION_REQUEST = "GET_PRODUCTS_BY_PUBLICATION_REQUEST";
export const GET_PRODUCTS_BY_PUBLICATION_SUCCESS = "GET_PRODUCTS_BY_PUBLICATION_SUCCESS";
export const GET_PRODUCTS_BY_PUBLICATION_FAIL = "GET_PRODUCTS_BY_PUBLICATION_FAIL";


export const LIST_PRODUCTS_USER_REQUEST = "LIST_PRODUCTS_USER_REQUEST";
export const LIST_PRODUCTS_USER_SUCCESS = "LIST_PRODUCTS_USER_SUCCESS";
export const LIST_PRODUCTS_USER_FAIL = "LIST_PRODUCTS_USER_FAIL";

export const UPDATE_PRODUCT_USER_REQUEST = "UPDATE_PRODUCT_USER_REQUEST";
export const UPDATE_PRODUCT_USER_SUCCESS = "UPDATE_PRODUCT_USER_SUCCESS";
export const UPDATE_PRODUCT_USER_FAIL = "UPDATE_PRODUCT_USER_FAIL";

export const DELETE_PRODUCT_USER_REQUEST = "DELETE_PRODUCT_USER_REQUEST";
export const DELETE_PRODUCT_USER_SUCCESS = "DELETE_PRODUCT_USER_SUCCESS";
export const DELETE_PRODUCT_USER_FAIL = "DELETE_PRODUCT_USER_FAIL";

// category constants
export const LIST_CATEGORY_REQUEST = "LIST_CATEGORY_REQUEST";
export const LIST_CATEGORY_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const LIST_CATEGORY_FAIL = "LIST_CATEGORY_FAIL";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";

export const REMOVE_CATEGORY_REQUEST = "REMOVE_CATEGORY_REQUEST";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAIL = "REMOVE_CATEGORY_FAIL";

// bookmark constant

export const ADD_BOOKMARK_REQUEST = "ADD_BOOKMARK_REQUEST";
export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS";
export const ADD_BOOKMARK_FAIL = "ADD_BOOKMARK_FAIL";

export const CHECK_BOOKMARK_REQUEST = "CHECK_BOOKMARK_REQUEST";
export const CHECK_BOOKMARK_SUCCESS = "CHECK_BOOKMARK_SUCCESS";
export const CHECK_BOOKMARK_FAIL = "CHECK_BOOKMARK_FAIL";

export const REMOVE_BOOKMARK_REQUEST = "REMOVE_BOOKMARK_REQUEST";
export const REMOVE_BOOKMARK_SUCCESS = "REMOVE_BOOKMARK_SUCCESS";
export const REMOVE_BOOKMARK_FAIL = "REMOVE_BOOKMARK_FAIL";

